### PR TITLE
Add helper method to verify if fingerprint is available

### PR DESCRIPTION
**Pull request by LuizGadao**
- Add helper method to verify if fingerprint is available. Now in app sample show corrected message error in "onDigitusError".

- bugfix setOnClickListener in Button app sample.

### CODE REVIEW

**Comment by afollestad** [comment]
@LuizGadao there's already a method to check if the device supports fingerprint authentication `Digitus. isFingerprintAuthAvailable()`.

Also, the button click listener being before `init()` doesn't matter. The button click code isn't executed until the user can see it and press it.

**Comment by LuizGadao** [comment]
@afollestad if device supports finger print but don't have any digital user register in device the method **isFingerprintAuthAvailable** return **false**. It's wrong because device support fingerprint. Are you agree?

About listener when you call **Digitus.init** your sample enter in **onDigitusError** before set listener to **Digitus.get().startListening** and discart listener in **REGISTRATION_NEEDED** to **openSecuritySettings**. It's don't async this away you need two click in button to **openSecuritySettings**.

Remove all digital user in your device and debug it.

**Comment by afollestad** [comment]
I'll look at this later.

For the button click listener, it's still no issue. It's an async callback, it doesn't execute until the user clicks the button. `init()` will be called long before `startListening()` regardless of the order they're called there.

**Comment by LuizGadao** [comment]
Yes, it's async. But enter in `onDigitusError` before set listener to `Digitus.get().startListening()` this way override listener to `openSecuritySettings`.

**Pull request closed without merging**
